name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r <(conda list --explicit || echo "") || true
          pip install pytest pyarrow scikit-learn pandas matplotlib seaborn

      - name: Run tests
        run: pytest -q

      - name: Smoke test reproduce
        run: |
          mkdir -p data/raw
          # create tiny fake dataset for smoke
          echo "age,glucose,target" > data/raw/diabetes.csv
          echo "50,100,0" >> data/raw/diabetes.csv
          echo "60,120,1" >> data/raw/diabetes.csv
          echo "55,130,0" >> data/raw/diabetes.csv
          make reproduce
