name: [![Run tests](https://github.com/bradneiman-ws/diabetes-capstone/actions/workflows/tests.yml/badge.svg?branch=main)](https://github.com/bradneiman-ws/diabetes-capstone/actions/workflows/tests.yml?query=branch%3Amain)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:   # 👈 enables manual runs from GitHub UI

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"   # you can list more versions if you want

    - name: Install package
      run: |
        pip install -e .
        pip install pytest

    - name: Run tests
      run: pytest -q
